version: "3.7"

services:
  rarimo-poh-db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=rarimo-poh
      - POSTGRES_PASSWORD=rarimo-poh
      - POSTGRES_DB=rarimo-poh-db
      - PGDATA=/pgdata
    volumes:
      - rarimo-poh-data:/pgdata
    ports:
      - "15432:5432"

volumes:
  rarimo-poh-data:
